### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gnunn1** [ErichDonGubler/dutils#1]
I'd like to use the csvwriter in Terminix (https://github.com/gnunn1/terminix), what's the license on this module?

**Comment by ErichDonGubler** [comment]
I'll make it Boost. :)

EDIT: This license should be pretty permissive, but let me know if there are any issues with it. Added with commit https://github.com/ErichDonGubler/dutils/commit/cd7db68e67a18d8a5ce4faa7f252e06d849a2a84.

**Comment by gnunn1** [comment]
Thanks!
